name: deploy
"on":
    push:
        branches:
            - main
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            # Setup
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  cache: "yarn"
            - run: yarn install --frozen-lockfile

            # Website bundle.
            - run: yarn run build
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: "${{ secrets.GITHUB_TOKEN }}"
                  firebaseServiceAccount: "${{ secrets.GCP_SERVICE_ACCOUNT }}"
                  channelId: live
                  projectId: keeb-43f9a

            # Search index.
            # TODO write index to file and read
            - uses: "google-github-actions/auth@v0"
              with:
                  credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT }}"
            - run: yarn run script:ingest
            - uses: "google-github-actions/upload-cloud-storage@v0"
              with:
                  path: 'dist/keyboard-index.json'
                  destination: 'keeb-43f9a-public'
                  parent: false
