name: deploy
"on":
    push:
        branches:
            - main
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            # Setup
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  cache: "yarn"
            - run: yarn install --frozen-lockfile

            # Website bundle.
            - run: yarn run build
            - id: hosting_deploy
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: "${{ secrets.GITHUB_TOKEN }}"
                  firebaseServiceAccount: "${{ secrets.GCP_SERVICE_ACCOUNT }}"
                  channelId: live
                  projectId: keeb-43f9a
            - run: |
                  echo ::notice title=test::test
                  echo ::notice title=hosting_files::"$HOSTING_FILES"
              env:
                  HOSTING_FILES: ${{ join(steps.hosting_deploy.outputs.urls, '\n') }}
